Manualis tesztek elkészültek
BME-MIT-IET/iet-hf-2023-grafadatbazis pull request #31
Opened 2023-05-31 17:23 UTC by davidok0

Megcsináltam azokat a teszteket, amiket fontosnak gondoltam, ManualTesting.pdf -ben vannak dokumentálva a tesztesetek.

2023-05-31 17:41 UTC, mate-bak requested changes
Doc mappába pl manualistesztek.md fájlba írd át a .pdf és .docx fájlok tartalmát.

2023-05-31 19:42 UTC, davidok0 commented
Átszerveztem a tesztek dokumentációját a manualistesztek.md fájlba, továbbá bővítettem a IET-HF fájlt a rá mutató linkkel.

2023-05-31 20:58 UTC, Mysteryusy approved these changes
Szerintem teljesen jó, bár megvárnám az eredeti Reviewer-től az approveot Merge előtt

2023-06-01 06:23 UTC, mate-bak approved these changes
lgtm

2023-06-01 09:22 UTC, merged